### ISSUE TITLE
`List` types don't work in the `Typing: New` form

### ISSUE THREAD

**Issue by Enteleform** [konodyuk/obsidian-typing#11]
For example, neither of these fields works:
```py
fields {
  tags:    List[Tag[dynamic=true]]
  choices: List[Choice["A", "B", "C"]]
}
```

When you try to create a `tag`, or choose one of the `choices`, the field just gets cleared out.

Another user ran into the same issue in this video at the linked timestamp:
[Obsidian Typing BETA Plugin!](https://www.youtube.com/watch?v=_A-DAQIDqTQ&t=925s)

**Comment by konodyuk** [comment]
You should use `Ctrl+Enter` or `Cmd+Enter` instead of `Enter` to submit a value when inside list.

**Comment by Enteleform** [comment]
Gotcha, thanks for the explanation!
