### ISSUE TITLE
Endless Icon Insertion at the Top of the File's Window

### ISSUE THREAD

**Issue by bezoro** [konodyuk/obsidian-typing#22]
The plugin is incorrectly adding multiple icons at the top of the file's window. As shown in the attached screenshot.
The more times I switch between _editing_ and _reading_ modes the more icons are inserted at the top.

v0.3.7

![export-0001](https://github.com/user-attachments/assets/72bfdf1d-74f2-4dd4-b722-28d6a88d1000)

**Comment by konodyuk** [comment]
@ArlonSwaders thank you for your time to figure out this issue! at the moment i have no time at all to handle even critical issues, so if you happen to feel like contributing something else or know someone else who wants, i'll be more than happy and can provide some dev docs and try to create a roadmap

**Comment by ArlonSwaders** [comment]
@konodyuk Thank you for merging my PR. I'd definitely be open to contribute more. I really like your approach and have been using it in my project for a while. That being said, I'm not a very familiar with typescript and am still learning it. Therefore, I might not be able to do big contributions yet.

I'd be more than happy to help out and try to fix issues when I come across them. I'm using the docs hosted at https://konodyuk.github.io/obsidian-typing. If you have any more documentation, I'd would be great if you could share them.

Thanks again, and see you on the next PR 😉
