### ISSUE TITLE
Idea: Instructions to install using Obsidian BRAT

### ISSUE THREAD

**Issue by A-F-V** [konodyuk/obsidian-typing#5]
This seems quite popular for installing plugins still in review process:
https://github.com/TfTHacker/obsidian42-brat

Has auto update as well.

Maybe there could be instructions added in the README to use this?

**Comment by konodyuk** [comment]
It took some time to get the plugin ready for Beta.

Anyway, the instruction is in the docs now: https://konodyuk.github.io/obsidian-typing/docs/installation
