### ISSUE TITLE
typing.otl missing

### ISSUE THREAD

**Issue by arminta7** [konodyuk/obsidian-typing#6]
Hello,

I can't seem to find the typing.otl file or the command to create it even after reloading and toggling it on and off. Am I doing something wrong?

**Comment by konodyuk** [comment]
Hey, I've just published a hotfix in 0.2.5 where `Typing: Create root schema` is available to comply with the [Quick start guide](https://konodyuk.github.io/obsidian-typing/docs/quick-start).

You can also create other `.otl` files in the vault root via `Typing: Create new .OTL file` command or in other directories by right-clicking them and selecting `New .otl file` in folder menu.
