### ISSUE TITLE
no type `Boolean`

### ISSUE THREAD

**Issue by auratheenby** [konodyuk/obsidian-typing#9]
Just went to try out the plugin and noticed that despite being in the documentation, `Boolean` isn't actually implemented as a field type. Kind of odd considering it's arguably the most basic one. I've checked and it's the only documented type missing. `true` and `false` also say "invalid type".

**Comment by konodyuk** [comment]
Yeah, it's a shame, hope to ship it soon. The thing is that it is such a simple feature that I've been focused on more challenging tasks.

**Comment by konodyuk** [comment]
It's implemented partially (without additional field type settings), so it will

**Comment by konodyuk** [comment]
Closing, as basic `Boolean` field type version has been implemented.

> `true` and `false` also say "invalid type".

This is also fixed, `true` and `false` literals can now be used as default values for boolean fields.

Picker setting for the field type will be implemented in the future versions, but this feature has low priority.
